### ISSUE TITLE
AllWatchesPage Page

### ISSUE THREAD

**Issue by SallamAltanna** [sallamTanna/north-twenty-two-private#67]
The user can browse this page when he clicks on "ALL WATCHES" option inside the menu under the "WATCHES" option. This page list all watches for both the women and men.

**Acceptance criteria for front-end**
- [x] The page should include the Header component #4 and Footer component #14 (already done).
- [x] The page should list all watches stored in a database, using the OneFeatured component #48 (already done) 
- [x] When the user clicks over any of these watches options, the user should be moved to DetailedWatchPage page #68  that displays more options about this watch.
- [x] The page should be responsive.

**Acceptance criteria for back-end**
- [x] ComponentDidMount() should fetch the whole watches from database using "getAllWatches" route.
- [x] Loading icon should appear till fetching the response from the back-end
