### ISSUE TITLE
DetailedWatchPage Page

### ISSUE THREAD

**Issue by SallamAltanna** [sallamTanna/north-twenty-two-private#68]
This page will show when the user clicks any watch he wants to buy. This page will present some details about the watch that the user wants to buy. 

**Acceptance criteria for front-end** 
- [x] The page should display some details about the watch, like name, price, and available wristbands color #79 .
- [x] The page should display the image of the watch, and slider displays the same watch with different colors #77 .
- [x] The page should allow the user to add the watch to his cart, and getting a message telling him that the watch is added to his cart successfully. 
- [x] The page should include Header component #4 and the Footer component #14 (already done).
- [x] Some extra information should be added, like the parts of the watch #81. 
- [x] The page should be responsive.  

**Acceptance criteria for back-end**
- [x] This page should receive the id of the watch from the URL, after that, we can search on this watch in the database using this id. The returned data is used to render the detailed page for the watch.
- [x] Use "displayWatchPage" #95  route to find the specific watch based on its id.
- [x] Loading icon should appear till fetching the response from the back-end
